version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: wordle-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./backend/data:/app/data:ro
    networks:
      - wordle-network
    restart: unless-stopped

  # Frontend service  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: wordle-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://nginx/api
      - NEXT_PUBLIC_WS_URL=ws://nginx/ws
    depends_on:
      - backend
    networks:
      - wordle-network
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: wordle-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - wordle-network
    restart: unless-stopped

networks:
  wordle-network:
    driver: bridge

volumes:
  ssl_data:
